<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ApplicationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('applications')->delete();
        
        \DB::table('applications')->insert(array (
            0 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-10 11:25:42',
                'cv' => 'Dr Mubarak Murtala Usman_1641835542.pdf',
                'email' => 'mmurtalamubarak@gmail.com',
                'firstname' => 'Mubarak',
                'hours' => NULL,
                'id' => 2,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Murtala Usman',
                'phone' => '2347039597355',
            'role' => 'Medical Officer (MO)',
                'title' => 'Mr.',
                'updated_at' => '2022-01-10 11:25:42',
            ),
            1 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-10 11:54:49',
                'cv' => 'DR AMINA\'S RESUME_1641837289.pdf',
                'email' => 'ameenahsalaudeen@gmail.com',
                'firstname' => 'Amina',
                'hours' => NULL,
                'id' => 3,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Salaudeen',
                'phone' => '08068274880',
                'role' => 'Medical officer',
                'title' => 'Mrs.',
                'updated_at' => '2022-01-10 11:54:49',
            ),
            2 => 
            array (
                'career' => 'MedeVolt Nursing',
                'created_at' => '2022-01-10 12:18:02',
                'cv' => 'Choice CV_1641838682.docx',
                'email' => 'otoghile.choice@yahoo.com',
                'firstname' => 'OTOGHILE',
                'hours' => NULL,
                'id' => 4,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'CHOICE',
                'phone' => 'O8065287784',
                'role' => 'Nursemidwife',
                'title' => 'Miss.',
                'updated_at' => '2022-01-10 12:18:02',
            ),
            3 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-10 13:39:11',
                'cv' => 'Cv_1641843551.docx',
                'email' => 'fatimamusashehu@gmail.com',
                'firstname' => 'Fatima',
                'hours' => NULL,
                'id' => 5,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Musa',
                'phone' => '08036251274',
                'role' => 'Doctor',
                'title' => 'Miss.',
                'updated_at' => '2022-01-10 13:39:11',
            ),
            4 => 
            array (
                'career' => 'MedeVolt Allied Health',
                'created_at' => '2022-01-10 14:36:53',
                'cv' => '12_1641847013.docx',
                'email' => 'jindujacobs91@gmail.com',
                'firstname' => 'CHIJINDU',
                'hours' => NULL,
                'id' => 6,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'PRINCEWILL',
                'phone' => '08064774091',
                'role' => 'LABOURATORY SCIENTIST',
                'title' => 'Mr.',
                'updated_at' => '2022-01-10 14:36:53',
            ),
            5 => 
            array (
                'career' => 'MedeVolt Allied Health',
                'created_at' => '2022-01-11 04:08:51',
                'cv' => 'OMatsuli’s cv_1641895731.pdf',
                'email' => 'omatsulimofe@gmail.com',
                'firstname' => 'Mofe',
                'hours' => NULL,
                'id' => 7,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Omatsuli',
                'phone' => '08145094691',
                'role' => 'A medical Laboratory scientist',
                'title' => 'Miss.',
                'updated_at' => '2022-01-11 04:08:51',
            ),
            6 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-11 05:02:12',
                'cv' => 'CV_1641898932.pages',
                'email' => 'fatimahyusuf96@gmail.com',
                'firstname' => 'Fatima',
                'hours' => NULL,
                'id' => 8,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Yusuf',
                'phone' => '08067365787',
                'role' => 'Medical officer',
                'title' => 'Miss.',
                'updated_at' => '2022-01-11 05:02:12',
            ),
            7 => 
            array (
                'career' => 'MedeVolt Allied Health',
                'created_at' => '2022-01-11 10:47:03',
                'cv' => 'no-file.pdf',
                'email' => 'mbyusufmbyusuf61@gmail.com',
                'firstname' => 'Muhammad',
                'hours' => NULL,
                'id' => 9,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Yusuf',
                'phone' => '08068131961',
                'role' => 'To carry out health services to the need',
                'title' => 'Mr.',
                'updated_at' => '2022-01-11 10:47:03',
            ),
            8 => 
            array (
                'career' => 'MedeVolt Allied Health',
                'created_at' => '2022-01-11 13:38:09',
                'cv' => 'IMG_1616707167616_1641929889.jpg',
                'email' => 'alasansunusi@outlook.com',
                'firstname' => 'Alasan',
                'hours' => NULL,
                'id' => 10,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Sunusi',
                'phone' => '08036286835',
                'role' => 'prevention, protection and promotion public Health',
                'title' => 'Mr.',
                'updated_at' => '2022-01-11 13:38:09',
            ),
            9 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-11 15:46:07',
                'cv' => 'no-file.pdf',
                'email' => 'garzalihudumuhammad@gmail.com',
                'firstname' => 'Garzali hudu',
                'hours' => NULL,
                'id' => 11,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Muhammad',
                'phone' => '08032186315',
                'role' => 'Environmental officers',
                'title' => 'Mr.',
                'updated_at' => '2022-01-11 15:46:07',
            ),
            10 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-11 15:52:07',
                'cv' => 'Dr Alye new cv_1641937927.docx',
                'email' => 'alyeiwuese@yahoo.com',
                'firstname' => 'Alye',
                'hours' => NULL,
                'id' => 12,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Benita Iwuese',
                'phone' => '08061609718',
                'role' => 'Locum medical officer',
                'title' => 'Miss.',
                'updated_at' => '2022-01-11 15:52:07',
            ),
            11 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-12 03:53:48',
                'cv' => 'CV Asmau Ambali_1641981228.doc',
                'email' => 'asmee2003@yahoo.com',
                'firstname' => 'ASMAÚ',
                'hours' => NULL,
                'id' => 13,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'AMBALI-BELGORE',
                'phone' => '08063453959',
                'role' => 'INTERPRET RADIOLOGICAL IMAGES',
                'title' => 'Mrs.',
                'updated_at' => '2022-01-12 03:53:48',
            ),
            12 => 
            array (
                'career' => 'MedeVolt Allied Health',
                'created_at' => '2022-01-12 12:44:26',
                'cv' => 'Current CV_1642013066.pdf',
                'email' => 'Abdulkareemmusa7@gmail.com',
                'firstname' => 'Musa Abdulkareem',
                'hours' => NULL,
                'id' => 14,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Halliru',
                'phone' => '+2348069464897',
                'role' => 'Radiographer',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 12:44:26',
            ),
            13 => 
            array (
                'career' => 'MedeVolt Allied Health',
                'created_at' => '2022-01-12 12:59:08',
                'cv' => 'MY CV PROPER_1642013948.docx',
                'email' => 'muxamm99@gmail.com',
                'firstname' => 'Muzammil',
                'hours' => NULL,
                'id' => 15,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Aminu',
                'phone' => '07060543937',
                'role' => 'Radiographer/sonographer',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 12:59:08',
            ),
            14 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-12 13:08:58',
                'cv' => 'WYCLIFFE ISHAYA_CV_1642014538.doc',
                'email' => 'wycliffeishaya10@yahoo.com',
                'firstname' => 'Ishaya',
                'hours' => NULL,
                'id' => 16,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Wycliffe',
                'phone' => '08032179985',
                'role' => 'Medical Doctor',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 13:08:58',
            ),
            15 => 
            array (
                'career' => 'MedeVolt Allied Health',
                'created_at' => '2022-01-12 13:17:10',
                'cv' => 'My CV_1642015030.docx',
                'email' => 'sharhabiluabubakarwarrah001@gmail.com',
                'firstname' => 'Abubakar',
                'hours' => NULL,
                'id' => 17,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Sharhabilu',
                'phone' => '08165935270',
                'role' => 'Diagnostic Radiographer',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 13:17:10',
            ),
            16 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-12 13:19:50',
                'cv' => 'Pdf CV-converted_1642015190.pdf',
                'email' => 'emmariokeke@gmail.com',
                'firstname' => 'Emmanuel',
                'hours' => NULL,
                'id' => 18,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Okeke',
                'phone' => '07037949299',
                'role' => 'To improve on HEALTHCARE of my patients via quality and patient friendly services',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 13:19:50',
            ),
            17 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-12 13:28:05',
                'cv' => 'Adamu Timothy JAWA. CV._1642015685.doc',
                'email' => 'jawatadamu@gmail.com',
                'firstname' => 'Timothy',
                'hours' => NULL,
                'id' => 19,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Jawa',
                'phone' => '07061912419',
                'role' => 'Medical consultation in paediatrics, Internal medicine, surgery, obstetrics and gynaecology..',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 13:28:05',
            ),
            18 => 
            array (
                'career' => 'MedeVolt Allied Health',
                'created_at' => '2022-01-12 13:53:19',
            'cv' => 'Resume (cv)_1642017199.docx',
                'email' => 'salisyusuf95@gmail.com',
                'firstname' => 'Salis',
                'hours' => NULL,
                'id' => 20,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Muhammad Yusuf',
                'phone' => '07010919510',
                'role' => 'Radiographer',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 13:53:19',
            ),
            19 => 
            array (
                'career' => 'MedeVolt Nursing',
                'created_at' => '2022-01-12 14:16:40',
                'cv' => 'adatinaa_1642018600.docx',
                'email' => 'Wycliffeadati@gmail.com',
                'firstname' => 'Adatina\'a',
                'hours' => NULL,
                'id' => 21,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Dewa',
                'phone' => '08034823315',
                'role' => 'Professional care giver',
                'title' => 'Miss.',
                'updated_at' => '2022-01-12 14:16:40',
            ),
            20 => 
            array (
                'career' => 'MedeVolt Nursing',
                'created_at' => '2022-01-12 14:57:37',
                'cv' => 'My CV_1642021057.doc',
                'email' => 'danielmaduwan2015@gmail.com',
                'firstname' => 'Maduwan',
                'hours' => NULL,
                'id' => 22,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Daniel',
                'phone' => '+2349030515524',
                'role' => 'Taking care of client who needs nursing care, collaborate with other professional to achieve optimal service delivery to client. Participate in relevant research work to promote client satisfaction.',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 14:57:37',
            ),
            21 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-12 15:55:23',
                'cv' => 'FATIMA GAILA SHUWA CV 2 2_1642024523.docx',
                'email' => 'timagaila@yahoo.com',
                'firstname' => 'Fatima',
                'hours' => NULL,
                'id' => 23,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Gaila',
                'phone' => '08108322949',
                'role' => 'Medical Officer',
                'title' => 'Miss.',
                'updated_at' => '2022-01-12 15:55:23',
            ),
            22 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-01-12 16:52:51',
                'cv' => 'Elijah_1642027971.docx',
                'email' => 'jameselijahwida@gmail.com',
                'firstname' => 'Elijah',
                'hours' => NULL,
                'id' => 24,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'James Wida',
                'phone' => '+2347067180878',
                'role' => 'An Emergency physician as I have worked in many different emergency settings and have gained all the necessary experience to practice effectively.',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 16:52:51',
            ),
            23 => 
            array (
                'career' => 'MedeVolt Allied Health',
                'created_at' => '2022-01-12 21:34:21',
                'cv' => 'Feb 15, Doc 1_1642044861.pdf',
                'email' => 'ahmadabdussalaminuwa@gmail.com',
                'firstname' => 'Ahmad',
                'hours' => NULL,
                'id' => 25,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Abdussalam Inuwa',
                'phone' => '07030022660',
                'role' => 'Radiographer',
                'title' => 'Mr.',
                'updated_at' => '2022-01-12 21:34:21',
            ),
            24 => 
            array (
                'career' => 'MedeVolt Nursing',
                'created_at' => '2022-01-13 01:14:49',
                'cv' => 'COSMOS CV_1642058089.docx',
                'email' => '00000murma@gmail.com',
                'firstname' => 'John',
                'hours' => NULL,
                'id' => 27,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Cosmos Amos',
                'phone' => '07061921845',
                'role' => 'Anaesthesia',
                'title' => 'Mr.',
                'updated_at' => '2022-01-13 01:14:49',
            ),
            25 => 
            array (
                'career' => 'MedeVolt Nursing',
                'created_at' => '2022-01-13 01:54:26',
                'cv' => 'leviticus Meky CV 01_1642060466.pdf',
                'email' => 'leviticusmeky222@gmail.com',
                'firstname' => 'Leviticus',
                'hours' => NULL,
                'id' => 28,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Meky',
                'phone' => '+2348082817435',
                'role' => 'Nutrition, paediatric and emergency',
                'title' => 'Mr.',
                'updated_at' => '2022-01-13 01:54:26',
            ),
            26 => 
            array (
                'career' => 'MedeVolt Nursing',
                'created_at' => '2022-01-13 02:27:53',
                'cv' => 'Innocent Stephen cv-1_1642062473.docx',
                'email' => 'stepheninnocent525@gmail.com',
                'firstname' => 'Innocent',
                'hours' => NULL,
                'id' => 29,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Stephen',
                'phone' => '09137739399',
                'role' => 'Nursing care of patients using the standard nursing process of assessment, Diagnosis, Outcome identification, planning, implications and Evaluation.

Carried out other roles as directed.',
                'title' => 'Mr.',
                'updated_at' => '2022-01-13 02:27:53',
            ),
            27 => 
            array (
                'career' => 'MedeVolt Doctors',
                'created_at' => '2022-07-29 22:55:55',
                'cv' => '1647457050799_DANIEL MELODY  CV 2_1648088659.pdf',
                'email' => 'bakale.mahmud@gmail.com',
                'firstname' => 'Mahmud',
                'hours' => NULL,
                'id' => 35,
                'job_id' => NULL,
                'job_type' => 'Full-Time',
                'lastname' => 'Bakale',
                'phone' => '+2348147384426',
                'role' => 'Hwelkfhoig',
                'title' => 'Dr.',
                'updated_at' => '2022-07-29 22:55:55',
            ),
        ));
        
        
    }
}