
            <nav id="site-navigation" class="navigation main-navigation clr" itemscope="itemscope" itemtype="https://schema.org/SiteNavigationElement" role="navigation" >

                <ul id="menu-main-menu" class="main-menu dropdown-menu sf-menu"><li id="menu-item-14889" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-14502 current_page_item menu-item-14889"><a href="{{route('welcome')}}" class="menu-link"><span class="text-wrap">Home</span></a></li><li id="menu-item-14908" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-14908"><a href="" class="menu-link"><span class="text-wrap">Careers<i class="nav-arrow fa fa-angle-down" aria-hidden="true" role="img"></i></span></a>
<ul class="sub-menu">
    <li id="menu-item-14872" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-14872"><a href="{{route('register-now')}}" class="menu-link"><span class="text-wrap">Register Now!</span></a></li> <li id="menu-item-15052" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15052"><a href="{{route('latest-roles')}}" class="menu-link"><span class="text-wrap">Latest Roles</span></a></li>  <li id="menu-item-14874" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-14874"><a href="{{route('doctors')}}" class="menu-link"><span class="text-wrap">MediVolt Doctors</span></a></li>    <li id="menu-item-14618" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-14618"><a href="{{ route('nursing')}}" class="menu-link"><span class="text-wrap">MediVolt Nursing</span></a></li>    <li id="menu-item-14951" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-14951"><a href="{{ route('allied-health')}}" class="menu-link"><span class="text-wrap">MediVolt Allied Health</span></a></li>
</ul>
</li><li id="menu-item-14909" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-14909"><a href="" class="menu-link"><span class="text-wrap">Solutions<i class="nav-arrow fa fa-angle-down" aria-hidden="true" role="img"></i></span></a>
<ul class="sub-menu">
    <li id="menu-item-17060" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17060"><a href="{{route('experience')}}" class="menu-link"><span class="text-wrap">MedeVolt Experience</span></a></li>  {{-- <li id="menu-item-20337" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-20337"><a href="{{route('f3year')}}" class="menu-link"><span class="text-wrap">MediVolt F3Year</span></a></li>  --}}  <li id="menu-item-18195" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-18195"><a href="{{route('direct')}}" class="menu-link"><span class="text-wrap">MediVolt Direct</span></a></li>  <li id="menu-item-17058" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17058"><a href="{{route('public')}}" class="menu-link"><span class="text-wrap">Public Sector</span></a></li>    <li id="menu-item-24580" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-24580"><a href="{{route('virtual-hospital')}}" class="menu-link"><span class="text-wrap">Virtual Hospital<i class="nav-arrow fa fa-angle-right" aria-hidden="true" role="img"></i></span></a>
    <ul class="sub-menu">
        <li id="menu-item-24581" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24581"><a href="{{route('virtual-register')}}" class="menu-link"><span class="text-wrap">Virtual Register</span></a></li>  </ul>
</li>   <li id="menu-item-17059" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17059"><a href="{{route('private')}}" class="menu-link"><span class="text-wrap">Private Sector</span></a></li>  {{-- <li id="menu-item-20569" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-20569"><a href="2xm-healthcare/index.html" class="menu-link"><span class="text-wrap">Medivolt Healthcare<i class="nav-arrow fa fa-angle-right" aria-hidden="true" role="img"></i></span></a>
    <ul class="sub-menu">
    MediVolt    </ul>
</li> --}}</ul>
</li><li id="menu-item-14927" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-14927"><a href="compliance/index.html" class="menu-link"><span class="text-wrap">Compliance<i class="nav-arrow fa fa-angle-down" aria-hidden="true" role="img"></i></span></a>
<ul class="sub-menu">
    <li id="menu-item-16967" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-16967"><a href="txm-paperless/index.html" class="menu-link"><span class="text-wrap">MediVolt Paperless<i class="nav-arrow fa fa-angle-right" aria-hidden="true" role="img"></i></span></a>
    <ul class="sub-menu">
        <li id="menu-item-17148" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17148"><a href="upload-your-documents/index.html" class="menu-link"><span class="text-wrap">Upload Your Documents</span></a></li>    </ul>
</li>   {{-- <li id="menu-item-17064" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17064"><a href="governance/index.html" class="menu-link"><span class="text-wrap">Governance</span></a></li>  <li id="menu-item-17219" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17219"><a href="revalidation/index.html" class="menu-link"><span class="text-wrap">Revalidation</span></a></li>  --}} <li id="menu-item-14578" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-14578"><a href="useful-documents/index.html" class="menu-link"><span class="text-wrap">Useful Documents</span></a></li>  <li id="menu-item-18293" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-18293"><a href="shop/index.html" class="menu-link"><span class="text-wrap">MediVolt Shop<i class="nav-arrow fa fa-angle-right" aria-hidden="true" role="img"></i></span></a>
    <ul class="sub-menu">
        <li id="menu-item-18297" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-18297"><a href="shop/standard-terms-conditions/index.html" class="menu-link"><span class="text-wrap">Standard Terms &#038; Conditions</span></a></li>        <li id="menu-item-18296" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-18296"><a href="returns-policy/index.html" class="menu-link"><span class="text-wrap">Returns Policy</span></a></li>      <li id="menu-item-18298" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-18298"><a href="consumer-terms-of-sales/index.html" class="menu-link"><span class="text-wrap">Consumer Terms of Sales</span></a></li>    </ul>
</li>   <li id="menu-item-17279" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17279"><a href="covid-19/index.html" class="menu-link"><span class="text-wrap">COVID-19</span></a></li></ul>
</li><li id="menu-item-14920" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-14920"><a href="support/index.html" class="menu-link"><span class="text-wrap">Support<i class="nav-arrow fa fa-angle-down" aria-hidden="true" role="img"></i></span></a>
<ul class="sub-menu">
    <li id="menu-item-24233" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-24233"><a href="news/index.html" class="menu-link"><span class="text-wrap">News</span></a></li>   <li id="menu-item-24416" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-24416"><a href="blog/index.html" class="menu-link"><span class="text-wrap">Blog</span></a></li>  {{-- <li id="menu-item-14767" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-14767"><a href="about-us/index.html" class="menu-link"><span class="text-wrap">TXM Family</span></a></li>    <li id="menu-item-14910" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-14910"><a href="refer-a-friend/index.html" class="menu-link"><span class="text-wrap">TXM Refer</span></a></li>   <li id="menu-item-14663" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-14663"><a href="xtra-miler-scheme/index.html" class="menu-link"><span class="text-wrap">Xtra Miler Scheme</span></a></li> --}}    {{-- <li id="menu-item-17002" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children dropdown menu-item-17002"><a href="report-a-concern/index.html" class="menu-link"><span class="text-wrap">Report a Concern<i class="nav-arrow fa fa-angle-right" aria-hidden="true" role="img"></i></span></a>
    <ul class="sub-menu">
        <li id="menu-item-17008" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17008"><a href="txm-complaints/index.html" class="menu-link"><span class="text-wrap">MediVolt Complaints</span></a></li>      <li id="menu-item-17009" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17009"><a href="safeguarding-concern/index.html" class="menu-link"><span class="text-wrap">Safeguarding Concern</span></a></li>      <li id="menu-item-17010" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17010"><a href="safety-concern/index.html" class="menu-link"><span class="text-wrap">Safety Concern</span></a></li>      <li id="menu-item-17011" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17011"><a href="on-site-issues/index.html" class="menu-link"><span class="text-wrap">On Site Issues</span></a></li> --}}  </ul>
</li>   <li id="menu-item-17441" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17441"><a href="contact-us/index.html" class="menu-link"><span class="text-wrap">Contact Us</span></a></li></ul>
</li>


            </ul>
            </nav><!-- #site-navigation -->
